### ISSUE TITLE
generate_data_statistics.py error

### ISSUE THREAD

**Issue by akjava** [akjava/Matcha-TTS-Japanese#1]
Traceback (most recent call last):
  File "/usr/local/bin/matcha-data-stats", line 8, in <module>
    sys.exit(main())
  File "/notebooks/Matcha-TTS-Japanese/matcha/utils/generate_data_statistics.py", line 115, in main
    text_mel_datamodule = TextMelDataModule(**cfg)
TypeError: TextMelDataModule.__init__() missing 1 required positional argument: 'load_durations'

**Comment by akjava** [comment]
the problem are forgot to add last line 
copy from ljspeech text and replace your needed
```
_target_: matcha.data.text_mel_datamodule.TextMelDataModule
name: ljspeech
train_filelist_path: data/LJSpeech-1.1/train.txt
valid_filelist_path: data/LJSpeech-1.1/val.txt


batch_size: 32
num_workers: 0
pin_memory: True
cleaners: [english_cleaners2]
add_blank: True
n_spks: 1
n_fft: 1024
n_feats: 80
sample_rate: 22050
hop_length: 256
win_length: 1024
f_min: 0
f_max: 8000
data_statistics:  # Computed for ljspeech dataset
  mel_mean: -5.536622
  mel_std: 2.116101
seed: ${seed}
load_durations: false
```
